plugins {
    id 'com.android.application'
}

android {
    namespace 'com.volumeppt.remote'
    compileSdk 34

    defaultConfig {
        applicationId 'com.volumeppt.remote'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            // 별도 서명 키 없이 바로 설치할 수 있도록 debug 키로 서명
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
